FROM node:17-alpine as base

WORKDIR /src
COPY package*.json /

ENV PORT 5000

EXPOSE $PORT

FROM base as production
ENV NODE_ENV=production
RUN npm ci
COPY . /
CMD ["node", "bin/www"]


FROM base as dev
ENV NODE_ENV=development
RUN npm install -g nodemon && npm install
COPY . /
CMD ["nodemon", "bin/www"]